services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/media/Prowlarr/Config:/config
      - /mnt/media/Prowlarr/Backup:/data/Backup
      - /mnt/media/Downloads:/data/downloads
    ports:
      - 9697:9696
    restart: unless-stopped
    networks:
      - app-network
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/media/Sonarr/Config:/config
      - /mnt/media/Sonarr/Backup:/data/Backup
      - /mnt/media/Sonarr/tvshows:/data/tvshows
      - /mnt/media/Downloads:/data/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - app-network
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/media/Radarr/Config:/config
      - /mnt/media/Radarr/Movies:/data/movies
      - /mnt/media/Downloads:/data/downloads
      - /mnt/media/Backup:/data/Backup
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network: null